### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by VanTuz5** [lonsty/xvideos-dl#28]
Where exactly do I need to look for the cookies the program requires?

**Comment by lonsty** [comment]
1. Go to https://xvideos.com, register and login with your account.
2. Open the developer mode of the browser, press `F12` for Chrome to open it.
3. Go to a personal page, for example: click `Account` -> `Videos I like` (https://www.xvideos.com/videos-i-like).
4. Find and COPY the Cookie:
![image](https://user-images.githubusercontent.com/42596173/115143692-6cb2a280-a07b-11eb-93ea-b26f976c556f.png)

**Comment by VanTuz5** [comment]
Thanks
