### ISSUE TITLE
Download in High Quality

### ISSUE THREAD

**Issue by Perturbator666** [lonsty/xvideos-dl#58]
I can't download videos in high quality.
A video that is 1080p comes in 360p.

**Comment by lonsty** [comment]
Added the feature to download high quality videos

1. Update this tool to latest: `pip install -U xvideos-dl`
2. Install `ffmpeg`
  - Ubuntu/Debian: `sudo apt install ffmpeg`
  - MacOS: `brew install ffmpeg`
