### ISSUE TITLE
does it work for windows?

### ISSUE THREAD

**Issue by JuanF007** [lonsty/xvideos-dl#70]
does it work for windows?  and how to run it

**Comment by lonsty** [comment]
Yes, it can work well.

1. Download and install Python >= 3.6.1 from https://www.python.org/
2. Open CMD or PowerShell, install this package by `pip install -U xvideos-dl`
3. Before run it, og in https://xvideos.com with your account, copy a full cookie
4. Run it in CMD or PowerShell by typing `xvideos-dl <single / favorites / uploaded / published video(s) link>`
5.  Paste your cookie when prompted
