### ISSUE TITLE
Windows操作系统无法使用

### ISSUE THREAD

**Issue by xm9572** [lonsty/xvideos-dl#74]
windows 下我下载了源码运行，根据错误，我安装了以下依赖：
pip install integv
pip install rich
pip install constant
然后还是报错：
Traceback (most recent call last):
  File "D:\code\xvideos-dl-master\xvideos_dl\xvideos_dl.py", line 18, in <module>
    from . import constant as c
ImportError: attempted relative import with no known parent package

请教一下，windows 下应该怎么用啊？

**Comment by lonsty** [comment]
这个工具是需要安装后使用的：

```shell
# 通过 pip 安装
pip install -U xvideos-dl

# 然后直接敲命令使用
xvideos-dl <URL ...>
```

如果非要直接跑代码也行，需要手动安装依赖包：

```shell
pip install typer rich beautifulsoup4 cursor integv requests
```

然后改动下 `xvideos_dl/__main__.py`，在末尾添加以下两行：

```
if __name__ == "__main__":
    app()
```

之后可以这样使用：

```shell
python -m xvideos-dl <URL ...>
```

**Comment by xm9572** [comment]
Thank you for your reply
