### ISSUE TITLE
Downloads not working for certain channels.

### ISSUE THREAD

**Issue by officialcactar** [lonsty/xvideos-dl#78]
## 🐛 Bug Report

When attempting to download certain channels nothing will happen, no error text or anything. 

## 🔬 How To Reproduce

1. `xvideos-dl https://www.xvideos.com/channels/heyzo-xxx`

### Environment

* OS: [e.g. Linux / Windows]
* Python version: 3.6.9

## 📈 Expected behavior

xvideos-dl downloads videos from given channel

**Comment by lonsty** [comment]
Add the feature to download highest quality video

**Comment by lonsty** [comment]
Since added a feature to download high quality videos, you need to install `ffmpeg`.
